# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_pet.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(873, 615)
        self.label_pet = QtWidgets.QLabel(Form)
        self.label_pet.setGeometry(QtCore.QRect(214, 244, 331, 291))
        self.label_pet.setMouseTracking(False)
        self.label_pet.setAutoFillBackground(False)
        self.label_pet.setText("")
        self.label_pet.setScaledContents(False)
        self.label_pet.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_pet.setWordWrap(False)
        self.label_pet.setOpenExternalLinks(False)
        self.label_pet.setObjectName("label_pet")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
